using System.IO;
using System.Linq;
using Coika.Data;
using UnityEditor;
using UnityEditor.AddressableAssets;
using UnityEngine;

namespace Coika.Tools
{
    /// <summary>
    /// Generates the final art of the 11 tiers (GDD §10) from <see cref="CoikaPalette"/>: the body sprites, the chart
    /// icons and the palette file. It imports them with the pixel-art settings, puts them and the atlas in the
    /// Theme-Cosmic Addressable group and assigns each body to its TierDefinition. Idempotent: running it again
    /// rewrites no file whose content has not changed. Own art, generated by this code (see Assets/Art/LICENSES.md).
    /// </summary>
    public static class PieceArtGenerator
    {
        /// <summary>
        /// Generates, imports, registers and assigns the art of every tier. Aborts with an error, changing nothing,
        /// when the 11 tiers or the Theme-Cosmic group are missing.
        /// </summary>
        [MenuItem("Coika/Generate Piece Art")]
        public static void Generate()
        {
            var tiers = PieceArtRules.FindTiers();
            if (tiers.Count != ThemeDefinition.TIER_COUNT)
            {
                Debug.LogError($"Expected {ThemeDefinition.TIER_COUNT} TierDefinition assets in {PieceArtRules.TIERS_FOLDER}, found {tiers.Count}.");
                return;
            }

            var settings = AddressableAssetSettingsDefaultObject.Settings;
            var group = settings != null ? settings.FindGroup(PieceArtRules.GROUP_NAME) : null;
            if (group == null)
            {
                Debug.LogError($"Addressables group '{PieceArtRules.GROUP_NAME}' not found.");
                return;
            }

            if (CoikaPalette.WriteGpl())
            {
                AssetDatabase.ImportAsset(CoikaPalette.GPL_PATH);
            }

            Directory.CreateDirectory(PieceArtRules.BODIES_FOLDER);
            Directory.CreateDirectory(PieceArtRules.ICONS_FOLDER);
            AssetDatabase.Refresh();

            foreach (var tier in tiers)
            {
                var bodyPath = $"{PieceArtRules.BODIES_FOLDER}/{PieceArtRules.BodyName(tier)}.png";
                RenameLegacySprite(tier, bodyPath);
                var bodySize = Mathf.RoundToInt(tier.DiameterUnits * TierDefinition.PixelsPerUnit);
                var bodyGuid = Import(bodyPath, bodySize, PieceArtRenderer.Render(tier.Index, bodySize, false));
                settings.CreateOrMoveEntry(bodyGuid, group, false, false);
                AssignSprite(tier, bodyGuid);

                var iconPath = $"{PieceArtRules.ICONS_FOLDER}/{PieceArtRules.IconName(tier)}.png";
                var iconGuid = Import(iconPath, PieceArtRules.ICON_SIZE, PieceArtRenderer.Render(tier.Index, PieceArtRules.ICON_SIZE, true));
                settings.CreateOrMoveEntry(iconGuid, group, false, false);
            }

            PieceAtlasSetup.Ensure();
            settings.CreateOrMoveEntry(AssetDatabase.AssetPathToGUID(PieceArtRules.ATLAS_PATH), group, false, false);

            AssetDatabase.SaveAssets();
            Debug.Log("Piece art is up to date.");
        }

        /// <summary>
        /// Moves the old placeholder sprite of a tier (Tier_XX_Name.png) to its final name, keeping its GUID so the
        /// tier reference stays valid.
        /// </summary>
        /// <param name="tier">The tier.</param>
        /// <param name="bodyPath">The final project path of the body sprite.</param>
        private static void RenameLegacySprite(TierDefinition tier, string bodyPath)
        {
            var legacyPath = $"{PieceArtRules.BODIES_FOLDER}/{tier.name}.png";
            if (File.Exists(legacyPath) && !File.Exists(bodyPath))
            {
                var error = AssetDatabase.MoveAsset(legacyPath, bodyPath);
                if (!string.IsNullOrEmpty(error))
                {
                    Debug.LogError(error);
                }
            }
        }

        /// <summary>
        /// Writes the PNG when it is missing or different, imports it and makes sure its importer follows
        /// <see cref="PieceArtRules"/>.
        /// </summary>
        /// <param name="path">Project path of the PNG.</param>
        /// <param name="size">Side of the square image in pixels.</param>
        /// <param name="pixels">The pixels to write.</param>
        /// <returns>The GUID of the imported asset.</returns>
        private static string Import(string path, int size, Color32[] pixels)
        {
            var texture = new Texture2D(size, size, TextureFormat.RGBA32, false);
            texture.SetPixels32(pixels);
            var png = texture.EncodeToPNG();
            Object.DestroyImmediate(texture);

            if (!File.Exists(path) || !File.ReadAllBytes(path).SequenceEqual(png))
            {
                File.WriteAllBytes(path, png);
            }

            AssetDatabase.ImportAsset(path, ImportAssetOptions.ForceSynchronousImport);

            var importer = (TextureImporter)AssetImporter.GetAtPath(path);
            if (PieceArtRules.GetImporterErrors(importer).Count > 0)
            {
                PieceArtRules.Apply(importer);
                importer.SaveAndReimport();
            }

            return AssetDatabase.AssetPathToGUID(path);
        }

        /// <summary>
        /// Points the sprite reference of a tier at the sprite with the given GUID. Does nothing when it already does.
        /// </summary>
        /// <param name="tier">The tier to modify.</param>
        /// <param name="spriteGuid">GUID of the sprite asset.</param>
        private static void AssignSprite(TierDefinition tier, string spriteGuid)
        {
            var serializedTier = new SerializedObject(tier);
            var guidProperty = serializedTier.FindProperty("_sprite.m_AssetGUID");

            if (guidProperty.stringValue == spriteGuid)
            {
                return;
            }

            guidProperty.stringValue = spriteGuid;
            serializedTier.ApplyModifiedPropertiesWithoutUndo();
            EditorUtility.SetDirty(tier);
        }
    }
}
