apply plugin: 'com.android.library'

android {
    namespace "com.coika.haptics"
    compileSdk getProperty("unity.compileSdkVersion") as int
    buildToolsVersion = getProperty("unity.buildToolsVersion")

    compileOptions {
        sourceCompatibility JavaVersion.valueOf(getProperty("unity.javaCompatibilityVersion"))
        targetCompatibility JavaVersion.valueOf(getProperty("unity.javaCompatibilityVersion"))
    }

    defaultConfig {
        minSdk getProperty("unity.minSdkVersion") as int
        targetSdk getProperty("unity.targetSdkVersion") as int
    }
}
